apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rabbitmq.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.azure.enabled }}
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "rabbitmq.fullname" . }}-azure-kv
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: 5672
          {{- if .Values.service.managementPort }}
            - name: management
              containerPort: 15672
          {{- end }}
          {{- if .Values.azure.enabled }}
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true

          command: ["sh", "-c"]
          args:
            - |
              set -eu

              export RABBITMQ_DEFAULT_USER="$(cat /mnt/secrets-store/rabbitmq-default-user)"
              export RABBITMQ_DEFAULT_PASS="$(cat /mnt/secrets-store/rabbitmq-default-pass)"

              exec docker-entrypoint.sh rabbitmq-server
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: RABBITMQ_PORT
              value: "{{ .Values.rabbitmq.port }}"
          {{- else }}
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.auth.username | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.auth.password | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
