{{- if ne .Values.environment "dev" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: keycloak-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - traefik-hiku-test.polandcentral.cloudapp.azure.com
{{- end }}