apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.clusterIP.port }}
      targetPort: http
    - name: mgmt
      port: {{ .Values.service.managementPort }}
      targetPort: mgmt