apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.edge.ingress.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ join "," .Values.edge.ingress.entrypoints | quote }}
    {{- if ne .Values.environment "dev" }}
    cert-manager.io/cluster-issuer: letsencrypt-staging
    {{- end }}
    {{- if .Values.edge.ingress.middlewares }}
    {{- $mws := list -}}
    {{- range .Values.edge.ingress.middlewares }}
      {{- if contains "@kubernetescrd" . }}
        {{- $mws = append $mws . -}}
      {{- else }}
        {{- $mws = append $mws (printf "%s-%s@kubernetescrd" $.Release.Namespace .) -}}
      {{- end }}
    {{- end }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," $mws | quote }}
    {{- end }}
    {{- if and .Values.edge.ingress.tls.enabled .Values.edge.ingress.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.edge.ingress.tls.clusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: traefik
  {{- if and .Values.edge.ingress.tls.enabled .Values.edge.ingress.host }}
  tls:
    - hosts:
        - {{ .Values.edge.ingress.host | quote }}
      secretName: {{ .Values.edge.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - {{- if .Values.edge.ingress.host }}
      host: {{ .Values.edge.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          {{- range .Values.edge.ingress.routes }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
