apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: dev
spec:
  headers:
    accessControlAllowOriginList:
      - "*"
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
      - "PUT"
      - "DELETE"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowCredentials: true
